### ISSUE TITLE
Download Folder?

### ISSUE THREAD

**Issue by aldksj34** [8qwe24657913/E-Hentai-Downloader-NW.js#1]
I don't know where the galleries are being downloaded - 下载的地方在哪里？你没说啊 :(

**Comment by 8qwe24657913** [comment]
nwjs.exe那里……

**Comment by aldksj34** [comment]
在 C:\Users\Admin\Downloads\nwjs-v0.15.2-win-x64 ... 这里没有下载

我发现它。 C:\Users\Admin\AppData\Local\Temp => Sort by date modified => nw####_#### => 文件夹编号

有点复杂，但它有用 - ¯\_(ツ)_/¯

**Comment by 8qwe24657913** [comment]
It seems that your comment is translated by a machine, which means you may not be familiar with Chinese. So let's use English.
The temporary directory of v0.12.3 is the same as the location of its executable……I'm sorry about that I didn't know it changed.

看起来你的评论是机翻的，就是说你可能不熟悉中文，所以让我们用英语交流吧
v0.12.3的临时文件夹和exe所在文件夹是一样的……抱歉我不知道它换了位置
