### ISSUE TITLE
能否给一个设置示例？

### ISSUE THREAD

**Issue by jiujingjqka** [8qwe24657913/E-Hentai-Downloader-NW.js#2]
能否给一个设置示例？我试了很多遍都不行，如图
![eh1](https://user-images.githubusercontent.com/30548498/28744019-0bf7ec38-7493-11e7-8505-df2ce1f6a75b.PNG)
1、URL是直接复制还是前面加g. ?
2、默认https 是不是要改成http？
3、cookie是只要灰字三项还是复制的全部？
![eh2](https://user-images.githubusercontent.com/30548498/28744042-a2ebe13a-7493-11e7-959e-26427ef02e03.PNG)
失败效果如图

**Comment by 8qwe24657913** [comment]
看了下，EH改了它的js，所以正则匹配失败了，已修正
URL直接复制不用改，cookie建议复制全部，虽然只复制灰字好像也可以……

PS: 我改了默认分支，nw.js v0.12.3请下载[这个](https://github.com/8qwe24657913/E-Hentai-Downloader-NW.js/raw/v0.13%2B/package.nw)，v0.13+就下载默认分支的就行了

**Comment by 8qwe24657913** [comment]
好吧，刚刚修了一个无法获取https内容的BUG……
